### ISSUE TITLE
Find reliable way of reading page load time

### ISSUE THREAD

**Issue by black-backdoor** [black-backdoor/MeOS#59]
sometimes I get crazy load times like this:
![Screenshot 2024-07-09 202215](https://github.com/black-backdoor/MeOS/assets/145743369/8606fecb-5457-411c-964d-4ef516020282)

**Comment by kabeer95** [comment]
@black-backdoor if its a paid issue , i would love to contribute .

**Comment by black-backdoor** [comment]
> @black-backdoor if its a paid issue , i would love to contribute .

Thank you for your offer, @kabeer95. However, as stated in the repository, this is a personal project that I would like to work on independently.
